public class partnerAPISobject {
    public class sObject_x {
        public String type_x;
        public String[] fieldsToNull;
        public String Id;
        @TestVisible private String[] type_x_type_info = new String[]{'type','urn:sobject.partner.soap.sforce.com',null,'1','1','false'};
        @TestVisible private String[] fieldsToNull_type_info = new String[]{'fieldsToNull','urn:sobject.partner.soap.sforce.com',null,'0','-1','true'};
        @TestVisible private String[] Id_type_info = new String[]{'Id','urn:sobject.partner.soap.sforce.com',null,'1','1','true'};
        @TestVisible private String[] apex_schema_type_info = new String[]{'urn:sobject.partner.soap.sforce.com','true','false'};
        @TestVisible private String[] field_order_type_info = new String[]{'type_x','fieldsToNull','Id'};
    }
}